server:
  port: 8082
spring:
  application:
    name: microservice-simple-provider
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    status-page-url-path: /info
    health-check-url-path: /health